version: '3'

volumes:
  mysql_data:
      driver: local
  realm-export.json:

services:
  mysql:
      image: mysql:5.7
      hostname: mysql
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
  keycloak:
      image: jboss/keycloak
      hostname: keycloak.local
      volumes:
        - ${PWD}/realm-export.json:/export/realm-export.json
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KEYCLOAK_IMPORT: /export/realm-export.json
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mysql
  rdpgw:
      build: .
      ports:
        - 9443:9443
      restart: on-failure
      depends_on:
        - keycloak
      healthcheck:
        test: ["CMD", "curl", "-f", "http://keycloak:8080"]
        interval: 30s
        timeout: 10s
        retries: 10