using System.ComponentModel.DataAnnotations;

namespace Rdpgw.Config;

/// <summary>
/// Cryptographic and federation settings for sessions, tokens, and gateway-to-gateway validation.
/// </summary>
public sealed class SecurityConfig
{
	/// <summary>
	/// An RSA private key in PEM format used to sign messages sent to or from the orchestrator, depending on the operating mode of the application.
	/// This key is used to ensure the authenticity and integrity of messages exchanged with the orchestrator.
	/// </summary>
	[Required]
	public string MessageSigningPrivateKey { get; set; } = string.Empty;

	/// <summary>
	/// An RSA public key in PEM format used to sign RDP cookie data. This key is used to verify the authenticity of cookies generated by the gateway, ensuring that they have not been tampered with.
	/// </summary>
	[Required]
	public string CookieSigningPublicKey { get; set; } = string.Empty;

	/// <summary>Gets or sets the PAA token encryption key retained for compatibility.</summary>
	[Required]
	[RegularExpression(@"^[\s\S]{32}$", ErrorMessage = "PAATokenEncryptionKey must be a 32-character string")]
	public string PAATokenEncryptionKey { get; set; } = string.Empty;

	/// <summary>Gets or sets the symmetric key used to sign PAA tokens.</summary>
	[Required]
	[RegularExpression(@"^[\s\S]{32}$", ErrorMessage = "PAATokenSigningKey must be a 32-character string")]
	public string PAATokenSigningKey { get; set; } = string.Empty;

	/// <summary>Gets or sets the symmetric key used to encrypt user tokens.</summary>
	[Required]
	[RegularExpression(@"^[\s\S]{32}$", ErrorMessage = "UserTokenEncryptionKey must be a 32-character string")]
	public string UserTokenEncryptionKey { get; set; } = string.Empty;

	/// <summary>Gets or sets the optional symmetric key used to sign user tokens.</summary>
	[Required]
	[RegularExpression(@"^[\s\S]{32}$", ErrorMessage = "UserTokenSigningKey must be a 32-character string")]
	public string UserTokenSigningKey { get; set; } = string.Empty;

	/// <summary>Gets or sets the symmetric key used to validate signed host query tokens.</summary>
	[Required]
	[RegularExpression(@"^[\s\S]{32}$", ErrorMessage = "QueryTokenSigningKey must be a 32-character string")]
	public string QueryTokenSigningKey { get; set; } = string.Empty;

	/// <summary>Gets or sets the shared bearer key used between primary and subservient gateways.</summary>
	[Required]
	[RegularExpression(@"^[\s\S]{32}$", ErrorMessage = "GatewaySharedKey must be a 32-character string")]
	public string GatewaySharedKey { get; set; } = string.Empty;

	/// <summary>Gets or sets the pre-shared key gateways use to authenticate their initial registration request.</summary>
	[Required]
	[RegularExpression(@"^[\s\S]{32}$", ErrorMessage = "GatewayRegistrationKey must be a 32-character string")]
	public string GatewayRegistrationKey { get; set; } = string.Empty;

	/// <summary>Gets or sets the issuer expected for signed host query tokens.</summary>
	public string QueryTokenIssuer { get; set; } = string.Empty;

	/// <summary>Gets or sets whether gateway tokens are bound to the client IP address.</summary>
	public bool VerifyClientIp { get; set; }

	/// <summary>Gets or sets whether encrypted user tokens can be embedded in generated usernames.</summary>
	public bool EnableUserToken { get; set; }

	/// <summary>
	/// Gets or sets the expiration time for signed gateway tokens. Defaults to 5 minutes.
	/// </summary>
	public TimeSpan ExpiryTime { get; set; } = TimeSpan.FromMinutes(5);
}