FROM rattydave/docker-ubuntu-xrdp-mate-custom:latest

RUN cd /etc/xrdp/ && \
    openssl req -x509 -newkey rsa:2048 -nodes -keyout key.pem -out cert.pem -days 3650 \
    -subj "/C=US/ST=VA/L=SomeCity/O=MyCompany/OU=MyDivision/CN=xrdp"

COPY xrdp.ini /etc/xrdp/xrdp.ini
